import { createContext, useContext, useState, useEffect } from 'react'

const AppContext = createContext()

export const translations = {
  en: {
    // Welcome
    tagline: 'Karnataka · AI Waste Classifier',
    tagline_kn: 'ಕರ್ನಾಟಕ · AI ತ್ಯಾಜ್ಯ ವರ್ಗೀಕರಣ',
    // Nav
    brand: 'WasteSmart',
    hi_user: 'Hi',
    logout: 'Logout',
    // Landing hero
    hero_title_1: 'Snap. Classify.',
    hero_title_2: 'Save the Planet.',
    hero_slogan: 'AI-powered waste classification with disposal guidance',
    hero_stat1_val: '20+', hero_stat1_lbl: 'Waste Types',
    hero_stat2_val: '100%', hero_stat2_lbl: 'Free',
    hero_stat3_val: '2', hero_stat3_lbl: 'Languages',
    // Feature cards
    feat_heading: 'What do you want to do?',
    feat_scan_lbl: 'Scan & Analyze', feat_scan_desc: 'AI-powered waste identification',
    feat_history_lbl: 'History', feat_history_desc: 'Your past scans and activity',
    feat_tips_lbl: 'Tips & Blogs', feat_tips_desc: 'Smart tips and latest articles',
    feat_blogs_lbl: 'Blogs', feat_blogs_desc: 'Latest in waste management',
    feat_quiz_lbl: 'Quiz', feat_quiz_desc: 'Test your eco knowledge',
    feat_barcode_lbl: 'Barcode Scanner', feat_barcode_desc: 'Scan product barcodes',
    feat_find_lbl: 'Find & Sell Scrap', feat_find_desc: 'Locate centers, check prices & sell scrap',
    feat_help_lbl: 'Find & Sell Scrap', feat_help_desc: 'Locate centers, check prices & sell scrap',
    feat_learn_lbl: 'Learn', feat_learn_desc: 'Waste management education',
    feat_community_lbl: 'Community', feat_community_desc: 'Groups, challenges & leaderboard',
    feat_marketplace_lbl: 'Sell Scrap', feat_marketplace_desc: 'List and sell your recyclables',
    feat_chat_lbl: 'AI Assistant', feat_chat_desc: 'Chat, voice and image analysis',
    feat_shop_lbl: 'Eco Shop', feat_shop_desc: 'Buy from verified eco-friendly brands',
    // Footer
    footer_tagline: 'AI-powered waste management for a cleaner Karnataka',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_contact: 'Contact',
    footer_copy: '© 2026 SmartWaste · Made for Karnataka',
    // Login
    welcome_back: 'Welcome back',
    create_account: 'Create account',
    reset_password: 'Reset password',
    sign_in_otp: 'Sign in with OTP',
    enter_otp: 'Enter OTP',
    continue_google: 'Continue with Google',
    or: 'or',
    email: 'Email address',
    password: 'Password',
    password_hint: 'Password (min 6 chars)',
    full_name: 'Full name',
    sign_in: 'Sign In',
    signing_in: 'Signing in...',
    creating: 'Creating...',
    sending: 'Sending...',
    verifying: 'Verifying...',
    forgot_password: 'Forgot password?',
    otp_login: 'Sign in with OTP',
    new_here: 'New here?',
    already_have: 'Already have an account?',
    back_signin: 'Back to sign in',
    reset_desc: "Enter your email and we'll send a reset link.",
    send_reset: 'Send Reset Link',
    otp_desc: "We'll email you a one-time code.",
    send_otp: 'Send OTP',
    otp_check: 'Check your email for the 6-digit code.',
    otp_placeholder: '6-digit OTP',
    verify_otp: 'Verify OTP',
    resend_otp: 'Resend OTP',
    confirm_password: 'Confirm password',
    identify: 'Identify Your Waste',
    upload_text: 'Click or drag an image here',
    upload_hint: 'JPG, PNG, WebP · Max 10MB',
    analyze_btn: 'Analyze with AI',
    analyzing: 'Analyzing...',
    analyzing_sub: 'Our AI is classifying your item',
    demo_mode: 'Demo Mode — Add GEMINI_API_KEY for real AI analysis',
    back: 'Back',
    recyclability: 'Recyclability',
    compostable: 'Compostable',
    reuse: 'Reuse',
    decompose: 'Decompose',
    sustain_score: 'Sustainability Score',
    sell_earn: 'Sell & Earn',
    description: 'Description',
    eco_tips: 'Eco Tips',
    points_earned: 'points earned',
    scan_again: 'Scan Another Item',
    yes: 'Yes', no: 'No',
    ex: 'Excellent — Highly sustainable',
    good: 'Good sustainability potential',
    mod: 'Moderate — consider alternatives',
    low: 'Low — dispose carefully',
    confidence: 'confidence',
    // ComingSoon
    coming_soon: 'Coming Soon',
    coming_desc: 'This feature is coming soon. Stay tuned!',
    back_home: 'Back to Home',
    // Scan extra
    identify_sub: 'Upload or capture an image — AI will identify all waste items',
    upload_gallery: 'Upload from Gallery',
    open_camera: 'Open Camera',
    capture: 'Capture Photo',
    close_camera: 'Close',
    found_items: 'Found {n} waste item(s)',
    bin_label: 'Bin Type',
    disposal_steps: 'Disposal Steps',
    carbon_title: 'Carbon Footprint',
    carbon_this: 'This item',
    carbon_wrong: 'If disposed wrong',
    carbon_saved: 'Saved by recycling',
    carbon_impact_msg: 'Proper disposal saves {x} kg CO₂ — equivalent to planting a tree.',
    carbon_overview_msg: 'These items produce {x} kg CO₂. Proper disposal significantly reduces this.',
    trees_needed: 'trees to offset',
    tab_dispose: 'Disposal', tab_carbon: 'Carbon', tab_diy: 'DIY Ideas',
  },
  kn: {
    tagline: 'ಕರ್ನಾಟಕ · AI ತ್ಯಾಜ್ಯ ವರ್ಗೀಕರಣ',
    tagline_kn: 'Karnataka · AI Waste Classifier',
    brand: 'WasteSmart',
    hi_user: 'ನಮಸ್ಕಾರ',
    logout: 'ಲಾಗ್ ಔಟ್',
    hero_title_1: 'ಫೋಟೋ ತೆಗೆಯಿರಿ. ವಿಂಗಡಿಸಿ.',
    hero_title_2: 'ಭೂಮಿ ಉಳಿಸಿ.',
    hero_slogan: 'ವಿಲೇವಾರಿ ಮಾರ್ಗದರ್ಶಿಯೊಂದಿಗೆ AI-ಚಾಲಿತ ತ್ಯಾಜ್ಯ ವರ್ಗೀಕರಣ',
    hero_stat1_val: '20+', hero_stat1_lbl: 'ತ್ಯಾಜ್ಯ ವಿಧಗಳು',
    hero_stat2_val: '100%', hero_stat2_lbl: 'ಉಚಿತ',
    hero_stat3_val: '2', hero_stat3_lbl: 'ಭಾಷೆಗಳು',
    feat_heading: 'ನೀವು ಏನು ಮಾಡಲು ಬಯಸುತ್ತೀರಿ?',
    feat_scan_lbl: 'ಸ್ಕ್ಯಾನ್ ಮತ್ತು ವಿಶ್ಲೇಷಣೆ', feat_scan_desc: 'AI-ಚಾಲಿತ ತ್ಯಾಜ್ಯ ಗುರುತಿಸುವಿಕೆ',
    feat_history_lbl: 'ಇತಿಹಾಸ', feat_history_desc: 'ನಿಮ್ಮ ಹಿಂದಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
    feat_tips_lbl: 'ಸಲಹೆಗಳು & ಬ್ಲಾಗ್', feat_tips_desc: 'ಸ್ಮಾರ್ಟ್ ಸಲಹೆಗಳು ಮತ್ತು ಇತ್ತೀಚಿನ ಲೇಖನಗಳು',
    feat_blogs_lbl: 'ಬ್ಲಾಗ್‌ಗಳು', feat_blogs_desc: 'ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆಯ ಇತ್ತೀಚಿನ ಸುದ್ದಿ',
    feat_quiz_lbl: 'ರಸಪ್ರಶ್ನೆ', feat_quiz_desc: 'ನಿಮ್ಮ ಪರಿಸರ ಜ್ಞಾನ ಪರೀಕ್ಷಿಸಿ',
    feat_barcode_lbl: 'ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನರ್', feat_barcode_desc: 'ಉತ್ಪನ್ನ ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    feat_find_lbl: 'ಹುಡುಕಿ & ಮಾರಿ', feat_find_desc: 'ಕೇಂದ್ರ ಹುಡುಕಿ, ಬೆಲೆ ತಿಳಿಯಿರಿ & ಸ್ಕ್ರ್ಯಾಪ್ ಮಾರಿ',
    feat_help_lbl: 'ಹುಡುಕಿ & ಮಾರಿ', feat_help_desc: 'ಕೇಂದ್ರ ಹುಡುಕಿ, ಬೆಲೆ ತಿಳಿಯಿರಿ & ಸ್ಕ್ರ್ಯಾಪ್ ಮಾರಿ',
    feat_learn_lbl: 'ಕಲಿಯಿರಿ', feat_learn_desc: 'ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ ಶಿಕ್ಷಣ',
    feat_community_lbl: 'ಸಮುದಾಯ', feat_community_desc: 'ಗುಂಪುಗಳು, ಸ್ಪರ್ಧೆಗಳು ಮತ್ತು ಲೀಡರ್‌ಬೋರ್ಡ್',
    feat_marketplace_lbl: 'ಸ್ಕ್ರ್ಯಾಪ್ ಮಾರಿ', feat_marketplace_desc: 'ನಿಮ್ಮ ಮರುಬಳಕೆ ವಸ್ತುಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ ಮಾರಿ',
    feat_chat_lbl: 'AI ಸಹಾಯಕ', feat_chat_desc: 'ಚಾಟ್, ಧ್ವನಿ ಮತ್ತು ಚಿತ್ರ ವಿಶ್ಲೇಷಣೆ',
    feat_shop_lbl: 'ಇಕೋ ಶಾಪ್', feat_shop_desc: 'ಪರಿಸರ ಸ್ನೇಹಿ ಬ್ರಾಂಡ್‌ಗಳಿಂದ ಖರೀದಿಸಿ',
    footer_tagline: 'ಸ್ವಚ್ಛ ಕರ್ನಾಟಕಕ್ಕಾಗಿ AI-ಚಾಲಿತ ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ',
    footer_privacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
    footer_terms: 'ಸೇವಾ ನಿಯಮಗಳು',
    footer_contact: 'ಸಂಪರ್ಕಿಸಿ',
    footer_copy: '© 2026 SmartWaste · ಕರ್ನಾಟಕಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ',
    welcome_back: 'ಮರಳಿ ಸ್ವಾಗತ',
    create_account: 'ಖಾತೆ ರಚಿಸಿ',
    reset_password: 'ಪಾಸ್‌ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ',
    sign_in_otp: 'OTP ಮೂಲಕ ಸೈನ್ ಇನ್',
    enter_otp: 'OTP ನಮೂದಿಸಿ',
    continue_google: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    or: 'ಅಥವಾ',
    email: 'ಇಮೇಲ್ ವಿಳಾಸ',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    password_hint: 'ಪಾಸ್‌ವರ್ಡ್ (ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು)',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    sign_in: 'ಸೈನ್ ಇನ್',
    signing_in: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    creating: 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    sending: 'ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...',
    verifying: 'ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...',
    forgot_password: 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?',
    otp_login: 'OTP ಮೂಲಕ ಸೈನ್ ಇನ್',
    new_here: 'ಹೊಸಬರೇ?',
    already_have: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    back_signin: 'ಸೈನ್ ಇನ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    reset_desc: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ, ನಾವು ರೀಸೆಟ್ ಲಿಂಕ್ ಕಳುಹಿಸುತ್ತೇವೆ.',
    send_reset: 'ರೀಸೆಟ್ ಲಿಂಕ್ ಕಳುಹಿಸಿ',
    otp_desc: 'ನಾವು ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ ಒಂದು-ಬಾರಿ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ.',
    send_otp: 'OTP ಕಳುಹಿಸಿ',
    otp_check: 'ನಿಮ್ಮ ಇಮೇಲ್‌ನಲ್ಲಿ 6-ಅಂಕಿ ಕೋಡ್ ಪರಿಶೀಲಿಸಿ.',
    otp_placeholder: '6-ಅಂಕಿ OTP',
    verify_otp: 'OTP ಪರಿಶೀಲಿಸಿ',
    resend_otp: 'OTP ಮರು-ಕಳುಹಿಸಿ',
    confirm_password: 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    identify: 'ನಿಮ್ಮ ತ್ಯಾಜ್ಯ ಗುರುತಿಸಿ',
    upload_text: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಎಳೆಯಿರಿ',
    upload_hint: 'JPG, PNG, WebP · ಗರಿಷ್ಠ 10MB',
    analyze_btn: 'AI ಯೊಂದಿಗೆ ವಿಶ್ಲೇಷಿಸಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    analyzing_sub: 'ನಮ್ಮ AI ವರ್ಗೀಕರಿಸುತ್ತಿದೆ',
    demo_mode: 'ಡೆಮೊ ಮೋಡ್ — ನಿಜವಾದ AI ಗಾಗಿ GEMINI_API_KEY ಸೇರಿಸಿ',
    back: 'ಹಿಂದೆ',
    recyclability: 'ಮರುಬಳಕೆ',
    compostable: 'ಕಾಂಪೋಸ್ಟ್',
    reuse: 'ಮರುಬಳಕೆ',
    decompose: 'ಕೊಳೆಯುವಿಕೆ',
    sustain_score: 'ಸುಸ್ಥಿರತೆ ಅಂಕ',
    sell_earn: 'ಮಾರಾಟ ಮಾಡಿ ಹಣ ಗಳಿಸಿ',
    description: 'ವಿವರಣೆ',
    eco_tips: 'ಪರಿಸರ ಸಲಹೆಗಳು',
    points_earned: 'ಅಂಕಗಳು ಗಳಿಸಿದ್ದೀರಿ',
    scan_again: 'ಇನ್ನೊಂದು ವಸ್ತು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    yes: 'ಹೌದು', no: 'ಇಲ್ಲ',
    ex: 'ಅತ್ಯುತ್ತಮ — ಹೆಚ್ಚು ಸುಸ್ಥಿರ',
    good: 'ಉತ್ತಮ ಸುಸ್ಥಿರತೆ',
    mod: 'ಮಧ್ಯಮ — ಪರ್ಯಾಯ ಪರಿಗಣಿಸಿ',
    low: 'ಕಡಿಮೆ — ಎಚ್ಚರಿಕೆಯಿಂದ ವಿಲೇವಾರಿ',
    confidence: 'ವಿಶ್ವಾಸ',
    coming_soon: 'ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ',
    coming_desc: 'ಈ ವೈಶಿಷ್ಟ್ಯ ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿದೆ. ನಿರೀಕ್ಷಿಸಿ!',
    back_home: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    identify_sub: 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಅಥವಾ ತೆಗೆಯಿರಿ — AI ಎಲ್ಲಾ ತ್ಯಾಜ್ಯ ವಸ್ತುಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ',
    upload_gallery: 'ಗ್ಯಾಲರಿಯಿಂದ ಅಪ್‌ಲೋಡ್',
    open_camera: 'ಕ್ಯಾಮೆರಾ ತೆರೆಯಿರಿ',
    capture: 'ಫೋಟೋ ತೆಗೆಯಿರಿ',
    close_camera: 'ಮುಚ್ಚಿ',
    found_items: '{n} ತ್ಯಾಜ್ಯ ವಸ್ತು(ಗಳು) ಕಂಡುಬಂದಿವೆ',
    bin_label: 'ಬಿನ್ ವಿಧ',
    disposal_steps: 'ವಿಲೇವಾರಿ ಹಂತಗಳು',
    carbon_title: 'ಕಾರ್ಬನ್ ಹೆಜ್ಜೆಗುರುತು',
    carbon_this: 'ಈ ವಸ್ತು',
    carbon_wrong: 'ತಪ್ಪಾಗಿ ವಿಲೇವಾರಿ ಮಾಡಿದರೆ',
    carbon_saved: 'ಮರುಬಳಕೆಯಿಂದ ಉಳಿತಾಯ',
    carbon_impact_msg: 'ಸರಿಯಾದ ವಿಲೇವಾರಿ {x} kg CO₂ ಉಳಿಸುತ್ತದೆ.',
    carbon_overview_msg: 'ಈ ವಸ್ತುಗಳು {x} kg CO₂ ಉತ್ಪಾದಿಸುತ್ತವೆ. ಸರಿಯಾದ ವಿಲೇವಾರಿ ಇದನ್ನು ಕಡಿಮೆ ಮಾಡುತ್ತದೆ.',
    trees_needed: 'ಮರಗಳು ಬೇಕು',
    tab_dispose: 'ವಿಲೇವಾರಿ', tab_carbon: 'ಕಾರ್ಬನ್', tab_diy: 'DIY ಆಲೋಚನೆಗಳು',
  }
}

export function AppProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('ws_lang') || 'en')
  const [theme, setTheme] = useState(() => localStorage.getItem('ws_theme') || 'dark')

  useEffect(() => {
    localStorage.setItem('ws_lang', lang)
  }, [lang])

  useEffect(() => {
    localStorage.setItem('ws_theme', theme)
    document.documentElement.setAttribute('data-theme', theme)
  }, [theme])

  const t = (key) => translations[lang]?.[key] ?? translations.en[key] ?? key

  const toggleTheme = () => setTheme(t => t === 'dark' ? 'light' : 'dark')
  const toggleLang = () => setLang(l => l === 'en' ? 'kn' : 'en')

  return (
    <AppContext.Provider value={{ lang, setLang, theme, toggleTheme, toggleLang, t }}>
      {children}
    </AppContext.Provider>
  )
}

export const useApp = () => useContext(AppContext)
